version: "3"
services:
  exius:
    build: ./
    expose:
      - 8080
      - 8081
    environment:
      - CONFIGNAME={...}
      - ADMINKEY={...}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    expose:
      - 5432