version: "3"
services:
  exius:
    build: ./
    environment:
      CONFIGNAME: example
      ADMINKEY: example
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      VIRTUAL_HOST: subdomain.domain
      LETSENCRYPT_HOST: subdomain.domain
      LETSENCRYPT_EMAIL: example@email.com
      VIRTUAL_PORT: 80
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    expose:
      - 5432
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    container_name: nginx-proxy
    networks:
      service_network:
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-acme:/etc/amce.sh
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-acme:/etc/amce.sh
networks:
  service_network:
volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-acme: