version: "3"
services:
  exius:
    image: ghcr.io/lanelewis/exius:latest
    environment:
      CONFIGNAME: data
      ADMINKEY: 1234
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - 80:8080
    networks:
      - service_network
    volumes:
      - ./data:/app/data
      - ./rclone:/root/.config/rclone
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    expose:
      - 5432
    networks:
      - service_network
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  service_network:
volumes:
  db-data: